### ISSUE TITLE
error on build with latest zig 0.11.0-dev.4229

### ISSUE THREAD

**Issue by ilmanzo** [ratfactor/ziglings#341]
steps to reproduce:

```
$ zig version ; git clone https://github.com/ratfactor/ziglings  ; cd ziglings ; zig build 
0.11.0-dev.4229+f1bd59876
Cloning into 'ziglings'...
remote: Enumerating objects: 3251, done.
remote: Counting objects: 100% (1211/1211), done.
remote: Compressing objects: 100% (258/258), done.
remote: Total 3251 (delta 1004), reused 1033 (delta 939), pack-reused 2040
Receiving objects: 100% (3251/3251), 721.74 KiB | 5.43 MiB/s, done.
Resolving deltas: 100% (2025/2025), done.
/tmp/ziglings/build.zig:384:16: error: expected type '@typeInfo(@typeInfo(@TypeOf(build.ZiglingStep.compile)).Fn.return_type.?).ErrorUnion.error_set![]const u8', found '?[]const u8'
        return try self.step.evalZigProcess(zig_args.items, prog_node);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ziglings/build.zig:353:68: note: function return type declared here
    fn compile(self: *ZiglingStep, prog_node: *std.Progress.Node) ![]const u8 {
                                                                   ^~~~~~~~~~
referenced by:
    make: /tmp/ziglings/build.zig:233:30
    create: /tmp/ziglings/build.zig:213:27
    remaining reference traces hidden; use '-freference-trace' to see all reference traces


```

**Comment by cgbur** [comment]
See #340
